---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "false"
        dynatrace/instrument: "false"
        pipeline.stage: prod-stable
        pipeline.build: 1.0.1.0005
        pipeline.project: sockshop
        support.contact: "jimmy.page@sockshop.com"
        support.channel: "#support-sockshop-middleware"
      labels:
        app.kubernetes.io/name: rabbitmq
        stage: production
        app.kubernetes.io/version: "1.0"
        tier: messaging
        product: sockshop
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management
          ports:
            - containerPort: 15672
              name: management
            - containerPort: 5672
              name: rabbitmq
          resources:
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter
          ports:
            - containerPort: 9090
              name: exporter
          resources:
      nodeSelector:
        kubernetes.io/os: linux
