apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: sockshop-production
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/name: orders-db
