apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sockshop-production
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: catalogue-db