apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        dynatrace/instrument: "false"
        pipeline.stage: prod-stable
        pipeline.build: 1.4.3.0054
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        app.kubernetes.io/name: catalogue-db
        stage: production
        app.kubernetes.io/version: "1.4"
        tier: data
        product: sockshop
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
        - name: catalogue-db
          image: dynatracesockshop/catalogue-db
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: fake_password
            - name: MYSQL_DATABASE
              value: socksdb
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: mysql
              containerPort: 3306
