apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: sockshop-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
