apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
  namespace: sockshop-staging
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "false"
        dynatrace/instrument: "false"
        pipeline.stage: staging
        pipeline.build: 1.0.2.0114
        pipeline.project: sockshop
        support.contact: "jimmy.page@sockshop.com"
        support.channel: "#support-sockshop-middleware"
      labels:
        app.kubernetes.io/name: rabbitmq
        stage: staging
        app.kubernetes.io/version: "1.0"
        tier: messaging
        product: sockshop
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
        resources:
          limits:
           cpu: "200m"
           memory: "256Mi"
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
        resources:
          limits:
           cpu: "200m"
           memory: "256Mi"
      nodeSelector:
        kubernetes.io/os: linux
