apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sockshop-staging
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: catalogue-db
