apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sockshop-staging
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        dynatrace/instrument: "false"
        pipeline.stage: staging
        pipeline.build: 2.0.0.6347
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: catalogue-db
        stage: staging
        version: "2.0"
        tier: data
        product: sockshop
    spec:
      containers:
        - name: catalogue-db
          image: dynatracesockshop/catalogue-db
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: fake_password
            - name: MYSQL_DATABASE
              value: socksdb
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: mysql
              containerPort: 3306
