---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: sockshop-staging
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: staging
        pipeline.build: 1.1.0.1578
        pipeline.project: sockshop
        support.contact: "john.doe@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app.kubernetes.io/name: orders
        stage: staging
        release: stable
        app.kubernetes.io/version: "0.5.0"
        tier: "business"
        product: "sockshop"
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
        - name: orders
          image: dynatracesockshop/orders:0.5.0
          env:
            - name: JAVA_OPTS
              value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
  namespace: sockshop-staging
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: orders
