---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: sockshop-staging
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: staging
        pipeline.build: 1.5.0.0073
        pipeline.project: sockshop
        support.contact: "tony.stark@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app.kubernetes.io/name: user
        stage: staging
        release: stable
        app.kubernetes.io/version: "0.5.0"
        tier: "business"
        product: "sockshop"
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
        - name: user
          image: dynatracesockshop/user:0.5.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          resources:
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
  namespace: sockshop-staging
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: user
