---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: sockshop-dev
spec:
  selector:
    matchLabels:
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: dev
        pipeline.build: 1.1.0.7904
        pipeline.project: sockshop
        support.contact: "john.doe@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app.kubernetes.io/name: shipping
        stage: dev
        release: stable
        app.kubernetes.io/version: "0.5.0"
        tier: "business"
        product: "sockshop"
        app.kubernetes.io/part-of: sockshop
    spec:
      containers:
      - name: shipping
        image: dynatracesockshop/shipping:0.5.0
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        resources:
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
  namespace: sockshop-dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: shipping
