apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-db
  namespace: sockshop-staging
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        dynatrace/instrument: "false"
        pipeline.stage: staging
        pipeline.build: 1.1.1.0022
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: orders-db
        stage: staging
        version: "1.1"
        tier: data
        product: sockshop
    spec:
      containers:
        - image: mongo
          name: orders-db
          env:
            - name: MONGODB_ADMIN_PASSWORD
              value: "password"
            - name: MONGODB_USER
              value: "user"
            - name: MONGODB_PASSWORD
              value: "password"
            - name: MONGODB_DATABASE
              value: "orders-db"
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /data/db
              name: orders-db-mongodata
      restartPolicy: Always
      volumes:
        - name: orders-db-mongodata
          persistentVolumeClaim:
            claimName: orders-db-mongodata
