apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: sockshop-staging
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: carts-db